### ISSUE TITLE
accessing mongodb json

### ISSUE THREAD

**Issue by carlarenee** [carlarenee/surfbuddy#2]
I imported a json into mongodb. I am having an issue with getting data back in json format: when I db.pools.find() I get an object back, but when I try to do this through my routes it console logs a weird text format of unrelated data. I think it has something to do with the way I imported the xml, it looks like an object that contains an array of objects. I've tried console logging key names for the objects but keep getting "undefined". 

**Here is my code to access the db:** 

`const { MongoClient } = require('mongodb');
const { ObjectID } = require('mongodb');
const dbConnection = 'mongodb://localhost:27017/surfbuddy';

function findPools(req, res, next) {
    MongoClient.connect(dbConnection, (err, db) => {
        if (err) return next(err);
        db.collection('pools')
        .find({})
        .toArray((arrayError, data) => {
            if (arrayError) return next(arrayError);
            res.pools = data;
            db.close();
            return next();
        });
        return false;
    })
    return false;
}
module.exports = {
    findPools
};`

When I console log res.pools, I get a weird format back. If I console log res.pools.name or res.pools._id or any other extension, I get undefined. 

@gittheking
@jasonseminara
@trevorpreston
@rapala61
@irwintsay

**Comment by rapala61** [comment]
Please push the latest version of your code
